using System;
using System.Collections.Generic;

public class PolicyBulk
{
    public string CommodityType { get; set; }
    public string Status { get; set; }
    public string ProductName { get; set; }
    public string ProductCode { get; set; }
    public string DealerName { get; set; }
    public string DealerCountry { get; set; }
    public string DealerCurrency { get; set; }
    public string DealerBranch { get; set; }
    public string DealerBranchCity { get; set; }
    public string DealerBranchServiceContractPerson { get; set; }
    public string DealerBranchServiceTelephoneNo { get; set; }
    public string DealerBranchServiceFax { get; set; }
    public string DealerBranchServiceEmail { get; set; }
    public string DealerBranchSalesContractPerson { get; set; }
    public string DealerBranchSalesTelephoneNo { get; set; }
    public string DealerBranchSalesFax { get; set; }
    public string DealerBranchSalesEmail { get; set; }
    public string InsurerName { get; set; }
    public string InsurerCode { get; set; }
    public string InsurerCountry { get; set; }
    public string VehicleVinNo { get; set; }
    public string Manufacturer { get; set; }
    public string ManufacturerCode { get; set; }
    public string ManufacturerWaranty { get; set; }
    public string EngineCapacityMeasureType { get; set; }
    public string ManufacturerWarantyCountry { get; set; }
    public string ManufacturerWarantyMonth { get; set; }
    public string ManufacturerWarantyStartDate { get; set; }
    public string ManufacturerWarantyKm { get; set; }
    public string MakeName { get; set; }
    public string MakeCode { get; set; }
    public string ModelName { get; set; }
    public string ModelCode { get; set; }
    public string ModelRiskStartDate { get; set; }
    public string CategoryName { get; set; }
    public string CategoryLength { get; set; }
    public string VehiclelCountryOfOrigine { get; set; }
    public string VehicleCylinderCount { get; set; }
    public string VehicleBodyType { get; set; }
    public string VehiclePlateNo { get; set; }
    public string VehicleModelYear { get; set; }
    public string VehicleFuelType { get; set; }
    public string VehicleAspiration { get; set; }
    public string VehicleVariant { get; set; }
    public string VehicleTransmission { get; set; }
    public string VehicleTransmissionTechnology { get; set; }
    public string PurchaseDate { get; set; }
    public string VehicleRegistrationDate { get; set; }
    public string VehicleEngineCapacity { get; set; }
    public string VehicleDriveType { get; set; }
    public string CommodityUsageType { get; set; }
    public string ElectronicCountryOfOrigine { get; set; }
    public string ElectronicSerialNo { get; set; }
    public string ElectronicModelYear { get; set; }
    public string ElectronicInvoiceNo { get; set; }
    public string ItemPrice { get; set; }
    public string DealerPrice { get; set; }
    public string ContractDealName { get; set; }
    public string ContractDealType { get; set; }
    public string ReinsurerName { get; set; }
    public string ReinsurerCode { get; set; }
    public string PromotionalDeal { get; set; }
    public string AutoRenewal { get; set; }
    public string DiscountAvailable { get; set; }
    public string DealStartDate { get; set; }
    public string DealEndDate { get; set; }
    public string PremiumTotal { get; set; }
    public string ClaimLimitation { get; set; }
    public string LiabilityLimitation { get; set; }
    public string ExtensionName { get; set; }
    public string ExtensionKm { get; set; }
    public string ExtensionMonth { get; set; }
    public string ExtensionHours { get; set; }
    public string PremiumBasedOnDescription { get; set; }
    public string PremiumBasedonCode { get; set; }
    public string BasicPremium { get; set; }
    public string OtherPremium { get; set; }
    public string AdditionalPremium { get; set; }
    public string SportsPremium { get; set; }
    public string FourByFourPremium { get; set; }
    public string MinimumPremium { get; set; }
    public string MaximumPremium { get; set; }
    public string RSAProviderName { get; set; }
    public string Region { get; set; }
    public string RateperAnum { get; set; }
    public string GrossPremium { get; set; }
    public string PremiumCurrencyType { get; set; }
    public string CoverType { get; set; }
    public string SalesPerson { get; set; }
    public string DealerPaymentCurrencyType { get; set; }
    public string CustomerPaymentCurrencyType { get; set; }
    public string PaymentMode { get; set; }
    public string CustomerFirstName { get; set; }
    public string CustomerLastName { get; set; }
    public string Nationality { get; set; }
    public string DateOfBirth { get; set; }
    public string CustomerCountry { get; set; }
    public string CustomerOccupation { get; set; }
    public string CustomerTitle { get; set; }
    public string CustomerGender { get; set; }
    public string CustomerMaritalStatus { get; set; }
    public string CustomerMobileNo { get; set; }
    public string CustomerPostalCode { get; set; }
    public string CustomerIdType { get; set; }
    public string CustomerIdNo { get; set; }
    public string CustomerIdIssueDate { get; set; }
    public string CustomerEmail { get; set; }
    public string CustomerType { get; set; }
    public string UsageType { get; set; }
    public string BusinessName { get; set; }
    public string BusinessAddress { get; set; }
    public string BusinessPhoneNo { get; set; }
    public string CustomerAddress { get; set; }
    public string CustomerCity { get; set; }
    public string HrsUsedAtPolicySale { get; set; }
    public string PolicyNo { get; set; }
    public string RefNo { get; set; }
    public string Comment { get; set; }
    public string Premium { get; set; }
    public string DealerPayment { get; set; }
    public string CustomerPayment { get; set; }
    public string SpecialDeal { get; set; }
    public string PartialPayment { get; set; }
    public string PolicySoldDate { get; set; }
    public string PolicyStartDate { get; set; }
    public string PolicyEndDate { get; set; }
    public string Discount { get; set; }
    public string DealerPolicy { get; set; }
    public string AutoApproval { get; set; }
}