version: 0.2

env:
  variables:
    SOLUTION: .\TAS.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.5

phases:
  install:
    commands:
      # Below is the URL for the MSI linked from https://www.iis.net/downloads/microsoft/web-deploy
      - Invoke-WebRequest -OutFile WebDeploy_amd64_en-US.msi https://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi
      - msiexec /i WebDeploy_amd64_en-US.msi /quiet
      # MSIExec will return before it is actually done - 30s seems to work...
      - Start-Sleep 30
  build:
    commands:
      - '& nuget restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe ./TAS.sln /p:DeployOnBuild=true /p:Configuration=Release'
artifacts:
  files:
    - .\TAS.Web\bin\*