version: 0.2

env:
  variables:
    SOLUTION: .\TAS.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.5

phases:
  build:
    commands:
      - '& nuget restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& msbuild -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'
artifacts:
  files:
    - .\TAS.Web\bin\Debug\*